# Generated by Django 5.1.2 on 2024-10-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
